codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70..100"

  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%

ignore:
  - "tests/*"
  - "**/__init__.py"
  - "app/main.py"  # si quieres ignorar el bootstrap

comment:
  layout: "reach, diff, files"
  behavior: default